### ISSUE TITLE
Duda sobre uso de JavaScript

### ISSUE THREAD

**Issue by sebaterrazas** [IIC2513/Syllabus#10]
El enunciado dice que se espera que sólo usemos HTML y CSS, entonces no podemos usar JS?

**Comment by valeeeriquelme** [comment]
Su uso no se restringe, pero no es obligatorio. Puedes usarlo, mientras cumplas con los requerimientos pedidos en el enunciado para HTML y CSS.

Mira también la sección Bonus.
