### ISSUE TITLE
Uso de .gitignore para no subir node_modules y "reducir" tamaño del .zip

### ISSUE THREAD

**Issue by paulmacguire** [IIC2513/Syllabus#102]
Hola! Para esta tarea se puede ocupar .gitignore para las carpetas node_modules? En la ayudantía de Koa del proyecto, el ayudante Andrés Cabezas nos dijo que hicieramos eso para que luego a la hora de subir los archivos estos no sean tan pesados. En caso de que se pueda, habría que crear un .gitignore para cada carpeta creada? Ya que en mi carpeta /frontend tengo una carpeta de node_modules, en mi carpeta de /backend también tengo un node_modules, y creo que también otro más. 

Quedo atento a sus respuestas :)

**Comment by inaguilera** [comment]
Creo que en este caso no aplica el .gitignore, debido a que la entrega es por buzón de canvas y no en un repositorio de git. Debieses solucionar esto al no agregar las carpetas `node_modules` en el zip correspondiente a tu entrega.  Quizás un ayudante podría corroborar esto.
