### ISSUE TITLE
Manejo de usuarios

### ISSUE THREAD

**Issue by IgnaciaGonzlez** [IIC2513/Syllabus#106]
Hola! Tengo la duda si para el manejo de usuarios se recomienda usar alguna librería (similar a Devise en Ruby on Rails) o si tenemos que hacer todo por nuestra cuenta.

**Comment by valeeeriquelme** [comment]
Para el manejo de usuario deben hacerlo por su cuenta. Para esta entrega sin embargo, no se pide manejo de sesión. Esto es algo que está en lo que se pedirá de la próxima entrega.
