### ISSUE TITLE
Error con instalación de Sequelize

### ISSUE THREAD

**Issue by paulmacguire** [IIC2513/Syllabus#107]
Hola! Hice el setup de Sequelize, y me tiró un error cuando corría yarn start:

![image](https://github.com/IIC2513/Syllabus/assets/101202383/9a38b707-6def-49ca-b55b-14e5f6e5383d)

Cómo lo podría solucionar? Miré la issue anterior pero este es otro error distinto al que ya resolvieron.

Sería de mucha ayuda si es que me dicen cómo puedo resolverlo, gracias de antemano :)

**Comment by juacob** [comment]
tengo el mismo problema

**Comment by valeeeriquelme** [comment]
hiciste yarn add de dotenv?

**Comment by paulmacguire** [comment]
Sí, ya lo hice. Te dejo un pantallazo:

![image](https://github.com/IIC2513/Syllabus/assets/101202383/79c58988-0d5d-4cb9-9ed3-9d6deb83af50)

**Comment by valeeeriquelme** [comment]
me muestras tus variables de entorno?
