### ISSUE TITLE
Problema con Swagger

### ISSUE THREAD

**Issue by EleaTriesToCode** [IIC2513/Syllabus#108]
Holis :D

He intentado añadir Swagger a mi proyecto, siguiendo el ejemplo dado en la pagina del enuciado (https://ljn.io/posts/swagger-for-a-koa-api)... pero no me funciona todavía y no entiendo porque :/

Eso es mi código de app.js :
![image](https://github.com/IIC2513/Syllabus/assets/98588172/9c0110d8-175e-4d24-bd62-643f24c47dc2)

Y eso es el error que me sale : 
![image](https://github.com/IIC2513/Syllabus/assets/98588172/5a8950c0-9533-4d55-854c-54c03feb9429)

Existen unos posts en stackoverflow con problemas similiares, pero en contextos más complejos y no logro entender bien los consejos dados... 

También si me prodrían confirmar que basta crear una "celda Swagger" para cada request/response del API para que la documentación sea completa ? O necesitamos también crear más test a parte ?

Gracias por su ayuda, saludos :)

**Comment by gonzaloi21** [comment]
Tenemos el mismo error!

**Comment by rlabb** [comment]
Por acá también

**Comment by valeeeriquelme** [comment]
Hola, aún no se muy bien a que se podría deber el error. Sin embargo, para no atrasar su desarrollo, sugiero que intenten documentando en [swaggerHub](https://app.swaggerhub.com/), de esa forma no deben integrar nada dentro de su api.

**Comment by valeeeriquelme** [comment]
Hola! les dejo este repo para que se guíen con la documentación con swagger. Está actualizada y no debería tener los mismos problemas que el otro link https://github.com/IIC2513/swagger-koa

**Comment by EleaTriesToCode** [comment]
Hola ! Gracias por la nueva guia, ahora podemos acceder a Swagger, pero con unos problemas todavia...

Se debe poder conectar Swagger a la base de datos ? Como hacer que los "Try it out" de Swagger hacen lo mismo que en Postman, modifican la DB y entregan el response body real obtenido ? O solo debe ser un catalogo informativo, y no se usaran los "Try it out" ? 

De momento, mi Swagger hace algo extraño en sus Try it out, envia la request pero de tal manera que el resultado obtenido para el mismo body es distinto que en Postman. O sea usando Postman todo funciona perfectamente, pero al hacer un Try it out en Swagger que supuestamente genera los mismos get/post, no funciona bien. 

Eso es por ejemplo lo que tengo en mi openapi.yml, con un get simple que debe darnos la lista de usuarios en la DB : 

![image](https://github.com/IIC2513/Syllabus/assets/98588172/866dcd30-bffe-4526-8891-76bbf05ee727)

Y el swagger : 
![image](https://github.com/IIC2513/Syllabus/assets/98588172/81044232-3f6a-4443-8da5-bf3110c28c1b)

En la consola se lee al hacer un try it out de este get en Swagger : 
![image](https://github.com/IIC2513/Syllabus/assets/98588172/434fc8ca-bcd9-466d-994b-1dedf8bc4352)

Pero en Swagger no aparece nada :/

Que estamos haciendo mal ? Se debe usar los Try it out de Swagger ? O mejor tenerlo solamente como un catalogo fijo informativo, y hacer solo los tests en Postman ? En este caso, la documentacion debe incluir una guia de tests a hacer en orden para ver todas las funcionalidades ?
 Lo mas facil para mi seria crear un readMe bien completo con unas propuestas de tests en orden, y quizas tener el swagger tambien pero solo como catalogo fijo. Se puede hacer eso ? 

Lo siento son muchas preguntas, pero no entiendo como funciona Swagger y hasta que punto debemos usarlo en esta entrega....

**Comment by valeeeriquelme** [comment]
No aparece ningún error en la consola del navegador que de indicios de por qué no se muestra?
