### ISSUE TITLE
Error ./models not found

### ISSUE THREAD

**Issue by juacob** [IIC2513/Syllabus#109]
Hola estamos teniendo un problema en que al hacer yarn start con todo el codigo hecho hasta el inicio de la capsula 3, nos arroja el siguiente error y no sabemos porque. Tenemos postgres corriendo y como se ve en las fotos models esta en la misma carpeta que index.
Gracias!

![models](https://github.com/IIC2513/Syllabus/assets/89426673/fc8e34b0-df95-4109-bb14-ed9bbe61aaa0)
 esta en la misma carpeta que index
![IMG_20230531_151138_907](https://github.com/IIC2513/Syllabus/assets/89426673/7420a618-6fe0-4aad-95ea-befaeb6320df)

**Comment by valeeeriquelme** [comment]
Me puedes mostrar una foto de su src/index.js y models/index.js?

**Comment by juacob** [comment]
> Hola, te refieres a la cápsula 3 de sequelize?

si, ahi tratamos de hacer yarn start y nos tiro el error, al final de la capsula 1 tampoco pudimos por otro error que sale en las issues pero seguimos con la 2 igual porque nos dejo correr los codigos

**Comment by juacob** [comment]
> Me puedes mostrar una foto de su src/index.js y models/index.js?

deberiamos tener un archivo index.js en models? ese no lo tenemos (solo tenemos los archivos de las entidades de nuestro juego). aqui  va la foto de index en src y de los contenidos de models.
![mode](https://github.com/IIC2513/Syllabus/assets/89426673/cd2fc684-f355-4ff5-ab76-7bc3764ef0ee)

![src](https://github.com/IIC2513/Syllabus/assets/89426673/0ffe1809-7d95-4605-9daa-6e1f2782aa50)

**Comment by valeeeriquelme** [comment]
Miren la última PR de el repositorio guess-who-backend (y vean la carpeta de models). No lo reconoce como modulo porque al ser una carpeta se va a buscar al archivo index.js 

Avísenme si les funciona!
