### ISSUE TITLE
Duda header CSS

### ISSUE THREAD

**Issue by rodrigoogalde** [IIC2513/Syllabus#11]
Hola!
Tengo una duda con respecto a un espacio blanco que me queda entre el header y un div que tengo al inicio.
Queria saber como quitar ese espacio en blanco.
Adjunto una imagen
Muchas gracias

El header tiene el siguiente diseño:
header {
  display: flex;
  align-items: center;
  padding: .5rem 3.75rem;
  background-color: orange;
}

y el div tiene:
#banner {
  height: 43.75rem;
  padding: 0 25%;
  background: url("banner.jpg") center center no-repeat;
  background-size: cover;
  text-align: center;
}

![image](https://user-images.githubusercontent.com/85193399/227792191-f09cac8a-74f8-4a17-97cc-7bfa4fdce437.png)

**Comment by valeeeriquelme** [comment]
El problema podría estar dado por como estás manejando la imagen. Por el estilo que me muestras entendería que tu intención es que la imagen quede centrada tanto vertical como horizontalmente. La imagen puede no estar alcanzado el height que definiste y por eso queda queda ese espacio en blanco. 

Evaluaría probar con otras formas de definir la altura de ese contenedor, teniendo en cuenta la relación con la imagen.
