### ISSUE TITLE
Problema con React usando Koa

### ISSUE THREAD

**Issue by LilianBernot** [IIC2513/Syllabus#110]
Por el proyecto, levanté un server koa como hicimos en la tarea del calculador. 
Mi problema es que mi main.jsx, que se ocupa de la generación del front con React, no se puede abrir. Tengo la siguiente error: 
<<<Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/jsx". Strict MIME type checking is enforced for module scripts per HTML spec.>>>

Mi .jsx está llamado así: <script type="module" src="../main.jsx"></script>  
Intenté cambiar tipo "module" con:
- "text/javascript": me da un error de sintaxis de '<'
- "text/jsx": el error desaparece pero no se visualiza nada

Intenté ocupar koaStatic de la siguiente manera: app.use(koaStatic(path.join(__dirname)));
También intenté ocupar @babel/preset-react, pero me parece complicado de manejar

Tienen una idea ?

**Comment by valeeeriquelme** [comment]
Por tu pregunta entiendo que estás tratando de servir el front desde el back. Si mi supuesto es correcto, lo que estás haciendo no es lo que se busca en el proyecto. Estamos trabajando con una API en la que el front se encuentra separado de esta y solo consume a través de requests.

Has posido ver las cápsulas del curso? En particular las que setean el proyecto en el back (koa y sequelize) y el front (react).

**Comment by LilianBernot** [comment]
Bueno, entiendo. Exactamente, intente hacer todo en el mismo proyecto, no pensé en la distinción con el repo de back

Gracias
