### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by robertoorrego** [IIC2513/Syllabus#111]
Hola! Estamos creando el modelo y las migraciones. Nuestro modelo contiene 4 tablas. Las primeras 3 se crean bien y la ultima tira el error "Cannot read properties of undefined (reading 'replace')". 

Nosotros no ocupamos el método replace en ninguna parte.

Intentamos encontrar el error con nuestra ayudante pero no lo logramos.

Se agradece todo tipo de ayuda!

**Comment by valeeeriquelme** [comment]
Hola, probaron con la solución que se menciona acá? https://stackoverflow.com/questions/54756410/sequelize-cli-cannot-read-property-replace-of-undefined-when-migrating-db

**Comment by robertoorrego** [comment]
Tuvimos que cambiar un poco el modelo. Invertir algunas asociaciones belongsTo a hasOne y viceversa.

La solución que mencionas no funcionó.
