### ISSUE TITLE
Entrega 2 Eslint y dotenv

### ISSUE THREAD

**Issue by Chumi-sun** [IIC2513/Syllabus#112]
¡Buenas tardes! Muchas gracias por su tiempo. Nos pasa que al correr Eslint nos pilla el siguiente error.

![imagen](https://github.com/IIC2513/Syllabus/assets/101197947/842e02a7-5794-4404-85ee-e28a53af089d)

Sin embargo, ese "process" que pilla como no definido, es el procces del .env, como se muestra a continuación

![imagen](https://github.com/IIC2513/Syllabus/assets/101197947/e89349f9-6de1-410a-8be6-b027f3909ec7)

Esto claramente es un caso especial del funcionamiento de la librería dotenv ¿Qué correspondería que hagamos en este caso?

**Comment by valeeeriquelme** [comment]
Hola, viste esta solución propuesta? https://stackoverflow.com/questions/50894000/eslint-process-is-not-defined
