### ISSUE TITLE
Restriccion Unique pero para un par de columnas...

### ISSUE THREAD

**Issue by EleaTriesToCode** [IIC2513/Syllabus#114]
Holis !

En nuestro juego es importante controlar que dos cartas no pueden ser en una misma posicion en una ciudad de un jugador - tenemos una tabla con las cartas en las ciudades, que tiene como columnas el id del jugador, la posicion, y detalles de las cartas. 
Para traducir este problema, pensabamos aplicar un restriccion unique a la par de keys jugadorID y posicion... Pero después de muchos intentos con propuestas en stackoverflow todavia no lo hemos logrado :/ 

Por ejemplo, eso de abajo parece que no funciona : 

![image](https://github.com/IIC2513/Syllabus/assets/98588172/697a49d0-c021-4d36-8a61-e67d1e01a7bc)
![image](https://github.com/IIC2513/Syllabus/assets/98588172/1a8e50e0-f84c-4530-817b-c1b3552beb4a)

Ustedes tendrian unos tips sobre como hacer eso ? Quizas mejor usar de validaciones, pero no entiendo bien como dentro de una validacion la columna posicion hacer referencia a la otra columna jugadorID...

Cualquier tip seria muy agradecido ! :D

**Comment by valeeeriquelme** [comment]
Por la forma en que  describes el problema asumo que están tratando de establecer una relación 1:1 entre las cartas y los jugadores. Osea, una carta puede pertenecer a un solo jugador y un jugador puede tener solo una carta (si no es así, no me hace sentido el unique). 

Como es una relación entre dos modelos, me apoyaría de las asociaciones para definir esa relación. Te recomiendo esta documentación para ver como aplicar asociaciones hasOne belongsTo (https://medium.com/@andrewoons/how-to-define-sequelize-associations-using-migrations-de4333bf75a7). Esta guía toma como ejemplo la relación Customer y Order, que se parece a su caso, pero en este caso un customer si puede tener más de una order, así que cuidado con eso. 

Para el caso de la posición, entiendo que este si es un atributo. En ese caso, ahí está bien hacerlo de la forma que muestras con unique, pero a nivel de endpoint (no de validación) agregaría una revisión para ver si hay otra carta en esa posición. Algo tipo, "findOne wehre position is (x,y)" y si hay una carta con esa posición, que no se permita la acción.

**Comment by valeeeriquelme** [comment]
Si ahora, es más claro. Enntiendo entonces que tienen una relación 1:n (un jugador tiene muchas cartas pero una carta puede ser solo de un jugador). No les digo que cambien la arquitectura, de hecho está bien como la definieron. El tema es que al ocupar unique en ambos atributos, están limitando a que en toda la tabla cartas-en-la-ciudad no pueda repetirse al atributo jugador, osea que un jugador solo podrá estar asociado a una carta, y no veo que eso responda a su arquitectura. 

La sugerencia es que manejen las asociaciones de la forma en que aparece en la guías que les mandé (en particular hasmany y belongs to one). Ya que de esa forma estarán levantando correctamente la arquitectura que planteas y se evitará a nivel de bdd que una carta pueda ser asociada a más de un jugador.
