### ISSUE TITLE
URGENTE De repente no puedo conectarme a ningun puerto de localhost desde el navegador

### ISSUE THREAD

**Issue by Rorro2408** [IIC2513/Syllabus#115]
Estaba testeando los diferentes endpoints de mi proyecto y todo iba bien, me podía conectar sin problema tanto desde google chrome como haciendo POST de postman. Reinicie mi computador y ahora no puedo conectarme a absolutamente ningun puerto en localhost.

He probado con distintos proyectos en koa que he hecho y se que funcionan, tambien he probado con proyectos de REACT, pero cada vez que me meto a localhost en el puerto indicado me sale que se rechazo la conexión.

La conección que mi app hace a la base de datos de posgres que escucha en localhost:5432 funciona por algún motivo, por lo que quizas el problema es del navegador, pero he probado tanto con chrome como con edge y en ninguno de los 2 ha resultado

**Comment by valeeeriquelme** [comment]
Puedes adjuntar una imagen de tu error?

**Comment by Rorro2408** [comment]
<img width="960" alt="image" src="https://github.com/IIC2513/Syllabus/assets/89088321/89bcbbd2-2556-4815-8b80-dacd273a8bdb">

**Comment by Rorro2408** [comment]
esto funcionaba antes de que reiniciase my pc, y mostraba "koa is working" en el navegador.
ahora no

**Comment by Rorro2408** [comment]
volví a reiniciar el pc y ahora vuelve a funcionar

**Comment by valeeeriquelme** [comment]
> volví a reiniciar el pc y ahora vuelve a funcionar
@Rorro2408 osea se recolvió?

**Comment by Rorro2408** [comment]
Si
