### ISSUE TITLE
Module "path" has been externalized for browser compatibility y Module "buffer" has been externalized for browser compatibility

### ISSUE THREAD

**Issue by vicente999** [IIC2513/Syllabus#122]
Hola! Mientras hacie el proyecto de la nada me salió este error (segun yo lo produjo vite) pero no se como resolverlo :(
Paso cuando me llego este mensaje en consola de vite  'i have this ✨ new dependencies optimized: koa/lib/response
4:00:58 PM [vite] ✨ optimized dependencies changed. reloading'
<img width="949" alt="image" src="https://github.com/IIC2513/Syllabus/assets/53841116/c34ca140-e6b0-466a-b892-f84f1176b037">

**Comment by valeeeriquelme** [comment]
Hola, pudieron resolverlo? si no es así, varias personas con problemas similares reportan habérlos solucionado ocupando la siguiente lib https://snyk.io/advisor/npm-package/vite-plugin-node-polyfills

**Comment by vicente999** [comment]
Sii, gracias!
