### ISSUE TITLE
Uso de JS en button

### ISSUE THREAD

**Issue by rodrigoogalde** [IIC2513/Syllabus#14]
Hola!
En el enunciado dice que la página debe ser estática, pero queria saber si puedo hacer uso de JS en un botón usando el siguiente código:

<button type="button" onclick="window.location.href='views/guide.html'">Ver más</button>

**Comment by valeeeriquelme** [comment]
Hola, no me es posible ver tu código. De todas formas, la respuesta debería ser similar a la issue #10 
Saludos!
