### ISSUE TITLE
Tarea 1: media query

### ISSUE THREAD

**Issue by gonzaloi21** [IIC2513/Syllabus#16]
Hola! En el enunciado aparece el siguiente punto para la página principal: "Utilizacion de media queries para asegurar que el sitio sea responsivo". Que son las media query? Y a que se refiere a que el sitio sea responsivo?

Gracias

**Comment by valeeeriquelme** [comment]
Hola, quedo disponible una cápsula que lo explica ([Cápsula HTML y CSS](https://github.com/IIC2513/Syllabus/blob/main/Proyecto/Capsulas/README.md)). 

De todas formas, en [esta página](https://www.w3schools.com/css/css_rwd_mediaqueries.asp) puedes ver más del tema. 

Saludos!
