### ISSUE TITLE
uso codigo taller tarea 1

### ISSUE THREAD

**Issue by tzehnder** [IIC2513/Syllabus#20]
Hola, estoy partiendo la tarea y tenia pensado utilizar algunas partes del codigo del taller, esto citando las partes que utilize, eso esta permitido?

**Comment by valeeeriquelme** [comment]
Está permitido

**Comment by pepinofdz** [comment]
hola! sobre esto, ¿está permitido utilizar como estructura básica general el taller pero cambiarlo para que sea personalizado? Por supuesto, especificando en la página o en el readme que se utilizó como base. Gracias de antemano
