### ISSUE TITLE
Duda header y navbar

### ISSUE THREAD

**Issue by jlizamajara** [IIC2513/Syllabus#21]
Hola! Tengo una duda sobre la diferencia entre header y navbar, estuve leyendo que a veces se coloca la navbar dentro del header, a veces no; pero no me queda muy clara la diferencia entre ambos y cuando se ocupan.
Muchas gracias!

**Comment by valeeeriquelme** [comment]
En relación a qué es lo más correcto, eso va a depender de como quieras estructurar tu página. Ocupar header nos da a entender que todo lo que esté contenido dentro es parte del encabezado. Más que un elemento en si, es una forma de "encapsular" otros elementos y darle más claridad semántica a tu código.

Navbar por otro lado si es un elemento (de hecho puedes utilizar el tag nav), se entiende que es un bloque que tendrá links a otras páginas, menus, etc.  

Tienes que ver que es lo que hace más sentido con tu solución y así decidir si la navbar va a estar contenida dentro de los elementos del header o no.
