### ISSUE TITLE
Duda uso código externo T1

### ISSUE THREAD

**Issue by jlizamajara** [IIC2513/Syllabus#24]
Hola!
En caso de que quiera usar código de una página, para implementarlo en algo específico ¿Está permitido? En caso de que estuviera, ¿se debe indicar específicamente en el README dónde se usó y el link correspondiente?

Muchas gracias :)

**Comment by valeeeriquelme** [comment]
Si. Todo lo que no sea creación propia debe ser referenciado en el README. No es necesario que indiques exactamente las líneas, pero si que funcionalidad implementaste basándote en este material.
