### ISSUE TITLE
Duda sobre lugares para citar información

### ISSUE THREAD

**Issue by aplaza2** [IIC2513/Syllabus#28]
Hola, quería preguntar qué tanto tenemos que crear la información de las fichas o si era posible casi copiar y pegar la información utilizada (considerando que el objetivo de la tarea es practicar creando página estáticas y no el contenido agregado en estas). Claro, todo lo agregado sería citado, pero también lo pregunto por el tipo de origen de la información agregada (por ejemplo, si podría citarse wikipedia o si se necesitaría citar páginas más acertadas del tema).

**Comment by valeeeriquelme** [comment]
Es más referenciar que citar. El contenido no se evalúa, así que puedes usar las fuentes que quieras.
