### ISSUE TITLE
T1 - Qué tanto tiene que cambiar el estilo según el tamaño de la pantalla?

### ISSUE THREAD

**Issue by MTaisa** [IIC2513/Syllabus#29]
Holaa, es básicamente eso, no entiendo muy bien a que se refieren con eso, si es por ejemplo que cuando la pantalla se reduce la disposición de los elementos cambie, o si es necesario cambiar colores y esas cosas?? Lo digo porque generalmente es sitios reales como que solo cambia la disposición de los elementos y no su paleta de colores.

**Comment by valeeeriquelme** [comment]
Lo que mencionas está bien. Podría ser que cambie el número de columnas de la "tabla" (como se muestra en la cápsula), cambiar textos de lugar para que se ajusten mejor, etc. Lo importante es que haya un manejo del cambio de tamaño.
