### ISSUE TITLE
duda sobre enunciado

### ISSUE THREAD

**Issue by IgnacioHqz** [IIC2513/Syllabus#30]
Hola! Tengo una duda sobre cómo debiese quedar la tarea.
No estoy seguro si estoy entendiendo bien lo que es una ficha. La idea es que la pagina principal muestre dos botones: contenido y acerca de? donde dentro de la págna de contenido deben mostrarse 5 fichas con la misma estructura? por ejemplo 5 tipos de insectos con su nombre, medidas, etc? O las fichas se entienden como páginas para cada insecto en este caso?
Me enredó un poco el enunciado. 
Gracias!

**Comment by EleaTriesToCode** [comment]
Me junto a este issue para preguntar otra cosa sobre el enunciado:
Menciona que las fichas son desplegables - eso significa que tenemos que hacer una selección para imprimir cada una a la vez (como en elegir una opción en una lista desplegable) o solo que las colocamos una tras la otra en la página simplemente?
No entiendo lo que se entiende con "desplegable" :0

**Comment by EleaTriesToCode** [comment]
Perdón no tenía aceso a internet cuando dejé este issue y me equivoqué de termino, el enunciado pide para "información estandarizada que se despliega en una estructura idéntica" : no me queda claro si eso significa simplemente que tenemos varios bloques similares uno después del otro / uno al lado del otro o algo más complejo ?
Lo siento es una pregunta tonta pero no soy chilena y creo que solo me falta entender bien la palabra :/

**Comment by valeeeriquelme** [comment]
@IgnacioHqz las fichas son como tarjetas. Deben desplegarse en una misma página. Por eso mismo se pide que usen grid y flexbox para que manejen como son ubicadas estas tarejtas.

**Comment by valeeeriquelme** [comment]
@EleaTriesToCode hola! lo que se busca es que resuelvan, usando flexbox o grid, cómo ubicar las fichas o tarjetas en la página. No se pide algo muy complejo, la idea es que quede ordenado y de fácil lectura (en especial en el caso en que la pantalla cambia de tamaño).
