### ISSUE TITLE
Duda Readme.md

### ISSUE THREAD

**Issue by 4n1t4** [IIC2513/Syllabus#32]
Hola, me surge una duda respecto a lo específico que se debe ser con lo pedido de "Eventual instalación", esto se refiere a explicar que el despliegue debe hacerse con alguna extensión como Liv Server o a otra cosa?

**Comment by valeeeriquelme** [comment]
En el enunciado se dejó una explicación general de lo que debería ir en un README. En el caso de la tarea, no debería haber algo que instalar. Por lo tanto, puedes ignorar esto. 

Saludos!
