### ISSUE TITLE
T1: Flex vs flexbox

### ISSUE THREAD

**Issue by Dafnemami** [IIC2513/Syllabus#33]
Hola! Veo que se puede usar display flex o flexblox. Me pregunto si usar flex cuenta como si usara flexbox, o debo estrictamente solo usar el segundo o grid? Saludos!

**Comment by Dafnemami** [comment]
Aprovecho de preguntar si para otros detalles dentro de las fichas puedo usar otros displays como table y table-cell

**Comment by valeeeriquelme** [comment]
al ocupar display:flex estás usando el modelo [flexbox](https://developer.mozilla.org/es/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox#:~:text=establecemos%20la%20propiedad%20del%20%C3%A1rea%20del%20contenedor%20display%20como%20flex%20o%20inline%2Dflex). 

No se recomienda el uso de table para manejar el display, a no ser que vayas a hacer una tabla. Te recomiendo que al igual que para las fichas, utilices flexbox o grid-layout.
