### ISSUE TITLE
T1: Encajonamiento y responsividad a cambios de tamano pantalla

### ISSUE THREAD

**Issue by Dafnemami** [IIC2513/Syllabus#34]
Hola!,

Tenía un div, que almacena mis fichas, usando flex-wrap y me funcionaba bien para el ajuste de estas en pantalla. Por mi forma de implementar las fichas decidí meter a cada ficha en otro div (todos estos nuevos divs siguen estando dentro de este div flex-wrap) Luego de eso lamentablemente perdí la responsividad de cada ficha a los cambios de tamano de la pantalla. Por qué puede estar pasando esto?(1)

(1) Intenté agregar diversos displays a los nuevos divs, pero siguen sin permitir que la ficha misma se haga más pequena cuando la página lo hace. Sí se mantuvo que cada ficha por si sola cambia su posición según el flex-wrap.

Espero se entienda, saludos!

**Comment by valeeeriquelme** [comment]
Cómo estás manejando el tamaño de las fichas? porcentaje? pixeles?

Cuando dices que estás ocupando flex-wrap, te refieres a que lo tienes definido como flex-wrap: wrap? definiste el display como flex?

**Comment by Dafnemami** [comment]
Hola!

El tamano de las fichas lo manejo como pixeles, en particular con width y max-height.

Si display:flex y flex-wrap:wrap.

**Comment by Dafnemami** [comment]
Me resolví la duda sola: un elemento contenido tenía ancho fijo y no en función de porcentaje. ugu
