### ISSUE TITLE
Control 1 Sección 1 Pregunta  Vacía

### ISSUE THREAD

**Issue by benjaaguila** [IIC2513/Syllabus#36]
Hola! Haciendo el control me ocurrió que una pregunta me salió en blanco. ¿Es problema mío o del control?(estoy usando Chrome).
<img width="576" alt="image" src="https://user-images.githubusercontent.com/89103342/229377698-c5814329-41bb-46a4-a92f-564446b90103.png">

**Comment by aaossa** [comment]
Gracias por el aviso, ya lo corregí. Si no me equivoco, debería arreglarse para quienes tomen el control de ahora en adelante. Por ahora, marca cualquier alternativa. Gracias!

PS: Solo por ser algo urgente es que respondí esta issue un domingo 😅
