### ISSUE TITLE
T2: Uso de librerias fs y path

### ISSUE THREAD

**Issue by NicolasOlmosQuiroga** [IIC2513/Syllabus#53]
¡Hola!, queria saber si para el desafio 2, estaba permitido usar las librerias fs y path de Node.js para trabajar con los archivos y directorios.

Eso seria, ¡muchas gracias!

**Comment by HernanCabreraPichuante** [comment]
claro que si! y cualquier biblioteca que esté disponible para el manejo de recursos en file systems del lado server
