### ISSUE TITLE
T2: Duda sobre las letras del abecedario

### ISSUE THREAD

**Issue by NicolasOlmosQuiroga** [IIC2513/Syllabus#54]
¡Hola!, estaba viendo el desafio 2 y me quedo la duda de que si el abecedario con el que tenemos que trabajar seria este:

"abcdefghijklmnñopqrstuvwxyzáéíóúü"

¿Estaria bien? Es que no me queda tan claro si se tienen que añadir mas elementos como ä, ö, o las mayusculas.

Eso seria, ¡muchas gracias!

**Comment by valeeeriquelme** [comment]
El abecedario que indicas es el correcto
