### ISSUE TITLE
Duda sobre emiteCertificado

### ISSUE THREAD

**Issue by FelipeMunozMoraga** [IIC2513/Syllabus#56]
Hola, En el enunciado se dice que en caso de que todo esté bien con el destino, se debe imprimir un certificado, y en caso de que no esté bien se debe imprimir el status con la restricción, dado que ese status viene de restricciones sanitarias, no entiendo en que caso dar uso al reject de emiteCertificado. Pensaba simplemente modificar emiteCertificado para que siempre que la llame sea resolve, pero no sé si eso es cambiar la naturaleza de la función, lo que está prohibido en el enunciado. Muchas gracias!

**Comment by Lexiesm** [comment]
Tengo la misma duda

**Comment by HernanCabreraPichuante** [comment]
El reject es en caso que falle la emisión del certificado (cualquier falla, por ejemplo un caso de interoperación, se cayó un router, no hay respuesta de alguna API y un sinfín de cosas que puede pasar en una arquitectura WEB)

**Comment by NicolasOlmosQuiroga** [comment]
> El reject es en caso que falle la emisión del certificado (cualquier falla, por ejemplo un caso de interoperación, se cayó un router, no hay respuesta de alguna API y un sinfín de cosas que puede pasar en una arquitectura WEB)

@HernanCabreraPichuante, una duda profesor, ¿en este caso tendriamos que simular con una probabilidad al azar que ocurra algun fallo? Por que no se me ocurre como hacer que se envie el reject sin tener que usar alguna variable para detectar un fallo, ¿serviria simplemente que justo abajo del resolve que dice que esta correcto, coloque otro resolve con la version fallida?
