### ISSUE TITLE
Duda arreglo Desafío 1 Tarea 2

### ISSUE THREAD

**Issue by Lexiesm** [IIC2513/Syllabus#58]
Hola consulta! en el enunciado del desafío 1 dice:

"Utilizar la siguiente estructura de datos un arreglo de objetos llamado restricciones que tiene la siguiente forma [ codigo: ABC12, destino: “SANTIAGO”, restriccion: 13, codigo: XYZ23, destino:”ARUBA”, restriccion: 57, ...., codigo: RST77,destino:”BRUSELAS, restriccion: 3 ]."

Se que la pregunta puede estar demás pero entonces en este arreglo cada triada no se encuentra separada por {}? es decir, de la forma:
[ {codigo: ABC12, destino: “SANTIAGO”, restriccion: 13}, {codigo: XYZ23, destino:”ARUBA”, restriccion: 57}, {....}, {codigo: RST77,destino:”BRUSELAS, restriccion: 3} ]." ?

Además de esto, los valores de código se encuentran como sale en el pdf del enunciado o van a estar entre comillas? es decir -> codigo: 'ABC12'.

De antemano muchas gracias!

**Comment by HernanCabreraPichuante** [comment]
La respuesta es corta, el objeto es de formato JSON. es decir, objetos dentro de un arreglo. por ello tiene razon, los objetos están entre {}. 
El código es un string asi que en rigor está entre comillas, tiene razón en su observación.
