### ISSUE TITLE
ejecución desafíos

### ISSUE THREAD

**Issue by Chumi-sun** [IIC2513/Syllabus#59]
dice que los desafíos se ejecutan usando node index.js. Sin embargo, cada desafío hace algo distinto con cosas distintas. ¿Eso significa que debe haber dos directorios distintos, cada uno con un index.js distinto o que al ejecutar index.js en consola pregunte a cuál desafío se quiere acceder? O queda a mi interpretación y como yo prefiera?

**Comment by valeeeriquelme** [comment]
Es mejor que manejes los desafíos por separado. Al no tener relación, no vale la pena que implementes algo como lo que indicas (interacción en consola). 

Puedes dejarlos en carpetas separadas.

**Comment by Chumi-sun** [comment]
Muchas gracias!
