### ISSUE TITLE
Desafío 1 [Tarea 2]

### ISSUE THREAD

**Issue by antoniafuica** [IIC2513/Syllabus#61]
Hola! Tengo una duda de cuando y como se reciben ciertos códigos. Por ejemplo: el código de destino y el array de las restricciones se recibe mediante un input?
Además si es que si, las restricciones se recibiran formato json o todo junto en un []?.

**Comment by HernanCabreraPichuante** [comment]
La forma en que se reciben los códigos/parámetros lo determina usted y lo debe documentar. 
Puede ser un input, no es problema, puede ser parámetros de ejecución que se pasan a Node o puede ser desde el mismo código "en duro" En esta parte, lo que les sea mas cómodo
Eso de "en duro" me refiero a que puedo escribir  nombreFuncion(codigo) en el mismo .js
Por otra parte el arreglo de objetos con {codigo, destino, resticción}. estará "en duro", deben indicar claramente donde está de manera que al corregir, se pueda cambiar ese arreglo por los casos de prueba que tendremos preparado.
Por supuesto cualquier solución de más "elegancia" será bienvenida.

Saludos
