### ISSUE TITLE
Manejo de errores con reject [Desafio1] [Tarea 2]

### ISSUE THREAD

**Issue by benjaaguila** [IIC2513/Syllabus#62]
Hola! 

Para el manejo de errores con reject en las funciones que retornan promesas. ¿Debemos manejarlo como error(utilizando new Error) o como string(pasando un string como parametro a reject)?

**Comment by HernanCabreraPichuante** [comment]
Buen dia.

En ese caso arroje un error que manipulará en el .catch (un mensaje que usted retorne) del  objeto promesa retornado a través del callback reject :-)

Saludos
