### ISSUE TITLE
reject desafío 1

### ISSUE THREAD

**Issue by Chumi-sun** [IIC2513/Syllabus#63]
Me piden lo siguiente: "Modificar el código de la función restriccionesSanitarias para incorporar el reject en caso de algún error (no de restricciones sanitarias, eso no es un error, es una condición)"

Pero restricciones sanitarias solo compara si un número es menor que otro. Entonces qué clase de error debería agregar con un reject?

**Comment by HernanCabreraPichuante** [comment]
Los erroes de un reject son, por lo general, casos de comunicaciones, imposibilidad de acceder a recursos, etc. Y eso lo puede controlar. Pense que una base de datos retorna que no pudo conectarse, password, invalida, etc.

**Comment by aurzuav** [comment]
Hay que hacerlo con una base de datos? No entiendo muy bien cómo obtengo el destino y restricción para cada código. 
gracias
