### ISSUE TITLE
T2: Duda sobre la ejecucion de node index.js de los desafios

### ISSUE THREAD

**Issue by NicolasOlmosQuiroga** [IIC2513/Syllabus#64]
¡Hola!, tenia una pregunta, para la correccion se menciona que se va a ejecutar "node index.js", ¿esto quiere decir que nosotros tenemos que llamar a la funcion dentro de nuestro index.js con nuestros ejemplos para que funcione? 

Lo que estaba haciendo en el desafio 2 (encriptacion), era usar process.argv para que la funcion se activara si el ayudante ponia en la terminal, `node index.js "mi_funcion" 1 / ejemplo.txt` o cualquier cosa relacionada con eso.

Pero no sabia si eso era lo correcto, tengo la misma duda en el desafio 1.

**Comment by Lexiesm** [comment]
Yo lo que hice fue crear el archivo package.json respectivo y luego en la tarminal coloco node index.js y me ejecuta bien

**Comment by HernanCabreraPichuante** [comment]
Que bueno que use argv, en ese caso usted debe entregar en el readme esas instrucciones para ejecución, la otra es la forma mínima que usaremos, pero no exclusiva. (también puede usar input si lo desea)

Bien por utilizar argumentos a Node. Lo importante es que su entrega esté lo suficientemente documentada para entender como ejecutar su solución 

Saludos

**Comment by juacob** [comment]
Hola no entendi bien esa parte tampoco, estaria correcto poner como instrucciones desde que carpeta se debe abrir VSC y asumir que el ayudante pondra run en este? que diferencia hay con que el ayudante lo corra como node index.js?
