### ISSUE TITLE
T2: Duda sobre usar promesas en el desafio 2

### ISSUE THREAD

**Issue by NicolasOlmosQuiroga** [IIC2513/Syllabus#65]
¡Hola!, queria saber si para el desafio 2 era necesario usar las promesas y rejects como en el desafio 1, o si simplemente era libre de usar una funcion que hiciera lo que se pide.

Eso seria, saludos.

**Comment by HernanCabreraPichuante** [comment]
Puede usarlo como le acomode, no hay una obligación en particular.
Ahora bien, leer un archivo grande puede ser Blocking I/O

Saludos!
