### ISSUE TITLE
Duda cuando falla certificado

### ISSUE THREAD

**Issue by mpalaciosc** [IIC2513/Syllabus#67]
Hola, en el enunciado del desafio 1 no me quedo claro una parte. Siempre (aunque haya restricciones) se llama a la funcion emiteCertificado y nosotros solo emitimos si es que no hay restriccion? O podemos hacer el codigo de manera que no sea necesario llamar a emitir certificado cuando hay restriccion.
En ese ultimo caso, cuando fallaria la emision del certificado?

**Comment by HernanCabrera** [comment]
buen día!
La parte relevante de esta pregunta es el manejo de la asincronía.
En particular, un reject puede ocurrir si hay algun erro como de interoperabilidad, asi que el reject es en casos de errores y una restricción de viaje no lo sería, sería una condición.
Explicado el propósito de la pregunta, la implementación tiene que tener el cuidado de manejar la asincronía, esa condición del runtime enviroment que es NodeJs y lo hace non blocking I/O.
Por otra parte, si hay restricciones para el viaje, lo adecuado es no emitir certificado
por ultimo, no olviden que hay omisiones y errores intencionales en planficacion.js que están para que ustedes reparen

Saludos!
