### ISSUE TITLE
Pregunta sobre modificacion de funciones

### ISSUE THREAD

**Issue by juacob** [IIC2513/Syllabus#69]
Hola queria saber si hay problema en modificar las funciones presentes en planificacion.js para agregarle un export antes del nombre y que puedan ser utilizadas por index.js.

Aprovecho tambien de preguntar si hay alguna diferencia entre correr el codigo de forma directa comparado con correrlo como dice el enunciado node index.js.

**Comment by HernanCabrera** [comment]
El archivo planificacion.js se DEBE modificar pues intencionalmente tiene omisiones y errores
Lo que no se puede cambiar es el callback del settimeout (Que es lo que hace esto asincrono

El código será probado en un ambiente con node y no desde un IDE.

Saludos
