### ISSUE TITLE
codigo viaje desafío 1

### ISSUE THREAD

**Issue by belenmatte** [IIC2513/Syllabus#71]
Tengo una duda con el código que hay que buscar en el desafío 1, el usuario tiene que ingresarlo como input o puedo definirlo en el index al principio y que el ayudante lo vaya cambiando para corregirlo? Tengo la misma duda con el arreglo de viajes, se puede definir en el index o tiene que ser de alguna manera especial?

Además no entiendo el parámetro delay de la función abrirSistema, hay que entregarlo y en base a que se decide su valor? si es menor a 3300 el programa no se debe ejecutar?

Y mi última pregunta es si puedo agregar más funciones en el archivo planificacion.js e importarlas todas en el index.

**Comment by HernanCabrera** [comment]
Sobre el primer punto, ambas soluciones son viables y correctas, puede elegir la que mas le acomode.
El parámetro delay de setTimeout no es relevante, lo importante es que nosotros podremos colocar cualquier valor al probarlo (razonable, claro está) la recomendación es que sea 3300, yo lo dejaría en ese valor, lo importante y dado que esta pregunta es de asincronía, es que sea perceptible.

El archivo planificacion.js lo puede modificar, es mas lo debe modificar en varias partes porque incluso hay errores intencionales. Lo que no debe tocar son los setTimeout, esos deben existir por lo de asincronia.

Por supuesto puede agregar funciones adicionales. 
Recuerde justificar todas sus decisiones de diseño.

Saludos
