### ISSUE TITLE
[Tarea 2] Robustez, errores

### ISSUE THREAD

**Issue by pepinofdz** [IIC2513/Syllabus#72]
Hola! No es necesario que manejemos errores de input para la tarea o si? Me refiero a que si por ejemplo en la parte 2 el path ingresado es incorrecto da lo mismo que el programa se caiga o debería ser impermeable a errores?
Quedo atento y muchas gracias de antemano

**Comment by HernanCabrera** [comment]
Si, en otros issues ya se advirtió que se debe controlar el ingreso y verificar las cosas mínimas de tipos de datos (incluido vacíos y otros) su solución debe ser robusta y en los errores mas típicos (n probaremos nada exótico ni rebuscado, pero si ingresar strings cuando deben haber números y cosas por el estilo, Tal vez no se caiga, recuerde el propósito de por qué las tecnologías Web tienen a ser resilientes
