### ISSUE TITLE
[T2] Desafío 1: formato restricciones

### ISSUE THREAD

**Issue by pepinofdz** [IIC2513/Syllabus#76]
Hola! No me quedó claro el formato en que tienen que ser las restricciones, revisé la issue #58 pero quedé más confundido. Debe ser un JSON? No podría ser implementado como una clase Restriccion, por ejemplo?
Además, se podría pedir ingresar las restricciones en cierto formato tipo csv por ejemplo?

Por supuesto, todo esto sería con explicación del funcionamiento e implementación en el README.

Quedo atento a cualquier cosa y muchas gracias de antemano!

**Comment by Dafnemami** [comment]
sii es un json. ve el taller 2 (https://github.com/IIC2513/Syllabus/tree/main/Talleres/Koa/src/data) ahí cachas como resolverlo :)
