### ISSUE TITLE
[Tarea 3] Operaciones con POST

### ISSUE THREAD

**Issue by nicolasgarciaes** [IIC2513/Syllabus#80]
Hola, tengo una duda con respecto a las operaciones que deben usar POST, para el caso de GET, es claro que se debe entregar en la ruta el tipo de operación, como lo menciona el ejemplo de "/suma/178/555". Pero para el caso de la resta y división, como se podría hacer la diferencia de la operación al momento de procesarla en el backend, es decir, yo puedo mandar una request del tipo /resta y que dentro del body vayan los números? y análogo para la división, o está prohibido mencionar la operación en la request. La duda va más que nada, para poder diferenciar las rutas de cada operación en el backend.

**Comment by valeeeriquelme** [comment]
No está prohibido lo que indicas. Osea puedes tener /resta y /division
