### ISSUE TITLE
[Tarea 3] Modularización y Middleware

### ISSUE THREAD

**Issue by MrBased** [IIC2513/Syllabus#81]
Actualmente para el backend tengo un `index.js` y `routes.js`. Este último trata las requests GET y POST y realiza las operaciones mandadas por la calculadora. ¿Está bien que básicamente el backend consista solo de mi `routes.js` para las operaciones o piden más formalidad con la modularización y uso de middleware más explícito? ¿Lo puedo dejar así o evalúan que tenga una estructura similar a el [taller de Koa](https://github.com/IIC2513/Syllabus/tree/e5d023e3fbf2721fb8a6605d43c1996aa5f5e30f/Talleres/Koa/src)?

**Comment by valeeeriquelme** [comment]
Para esta tarea no es necesaria la modularización. Esto se evaluará en el proyecto.
