### ISSUE TITLE
[Tarea 3] Operaciones múltiples simultaneas

### ISSUE THREAD

**Issue by aplaza2** [IIC2513/Syllabus#82]
Hola, quería preguntar si debemos manejar que se puedan ingresar varias operaciones a la vez en la calculadora (por ejemplo: 2+4*5). En caso de que haya que manejarlo, ¿podemos hacerlo con la función _eval()_? (siendo llamado desde el método de la api del primer símbolo identificado en la operación).

**Comment by bcalfaro** [comment]
Me sumo a la pregunta
