### ISSUE TITLE
[T3] Manejo de errores.

### ISSUE THREAD

**Issue by nicolasgarciaes** [IIC2513/Syllabus#85]
![image](https://github.com/IIC2513/Syllabus/assets/89041932/d453733a-59b2-4769-90c1-084037d3d5ce)
Se menciona en el enunciado que el front debe manejar algunos errores, como lo es el caso de "*777". Para estos casos, se debe mostrar en la consola el error? o con algún tipo de modal? en caso de ser asi, se podría usar React-Toastify? 

Luego para el caso del backend, por ejemplo, la división por 0, la consola del servidor debe mostrar el error? o se debe mandar al frontend el error y que el frontend lo muestre?

**Comment by valeeeriquelme** [comment]
El manejo de errores no se va a evaluar a nivel de consola (ni front ni back). A nivel de inputs permitidos, eso lo pueden manejar limitando los caracteres que se reciben o estableciendo reglas para revisar si el nuevo caracter respeta la semántica correcta (y en caso de no respetarlo, no permitir su ingreso).

La división por cero en el back se revisará a nivel de código.
