### ISSUE TITLE
Problemas con Puerto 80

### ISSUE THREAD

**Issue by Juancagp** [IIC2513/Syllabus#87]
Hola, al hacer listen al puerto 80 me sale el siguiente error: 
<img width="422" alt="image" src="https://github.com/IIC2513/Syllabus/assets/81201399/a2b56253-1f19-4ebe-beae-9dda0f2d118a">
buscando en internet no encontré alguna respuesta concia, por lo que no me quise arriesgar a instalar otras cosas. Que se puede hacer?

**Comment by angegazitua** [comment]
¡Hola! Yo tengo el mismo problema, me sale que tengo permiso denegado para ese puerto...
![image](https://github.com/IIC2513/Syllabus/assets/80768594/8422708d-f3c5-4610-923a-823397bb52d3)

¿Qué se puede hacer?

**Comment by valeeeriquelme** [comment]
Pueden ocupar otro puerto, no se va a evaluar que usen el 80
