### ISSUE TITLE
[Tarea 3] Entrega con React

### ISSUE THREAD

**Issue by Madauy** [IIC2513/Syllabus#88]
Hola, tengo una duda. Si realizo el frontend con React, debo entregar solo el build de la aplicación o todo el código? Además quería mencionar que en el enunciado dice que el ayudante corregirá ejecutando el index.html en el navegador, sin embargo si se hace con react se debe levantar un live server y no funcionaría solo abriendo el index.html.

**Comment by valeeeriquelme** [comment]
Deben entregar todo el código. Sobre como se va probar, es verdad lo que indicas. Con que especifiques en el readme como se deben ejecutar tus archivos está ok.
