### ISSUE TITLE
[Tarea 3] Forma de correr la página

### ISSUE THREAD

**Issue by camibennett** [IIC2513/Syllabus#89]
En el enunciado sale "Para probar este programa el ayudante ejecutará index.html en su browser y todo el resto debiese funcionar sin problemas." Puedo especificar en el readme que la tarea se corre con nodemon back/index.js (usando koa-static)? De no ser así, como puedo hacer para que al abrir index.html se corra también el backend?

Muchas gracias de antemano y quedo atenta.

**Comment by valeeeriquelme** [comment]
Hola. El back debe ser desarrolla aparte del front. Por lo tanto, para ambos deben seer servidos/hosteados/levantados en servidores locales aparte. Eso significa que no va a ocurrir que cuando corras el index también se va a levantar tu back. 

Si tu front lo haces con html/js (no react), puedes usar live server. En el back, por otra parte, para correrlo lo puedes hacer como se muestra en las cápsulas y talleres con nmp start o yarn start.

En esa línea, no debes usar koa-static.
