### ISSUE TITLE
Navbar e Index 

### ISSUE THREAD

**Issue by luzmagurzua** [IIC2513/Syllabus#9]
¡Hola!

Hice un archivo html y css sólo para la navbar y ahora quiero "Linkearla" al index.html para que se vea todo junto. La verdad es que no sé si realmente se puede hacer (o si es recomendable). Será mejor hacer la navbar directamente en index.html? 

Gracias desde ya.

**Comment by valeeeriquelme** [comment]
Sin javascript no es posible hacer lo que estás pensando. Para que la navbar esté en todos los archivos html, tienes que agregar el código de la navbar en todos los archivos html.
