### ISSUE TITLE
IMPORTANTE T3: Manejo erro de CORS

### ISSUE THREAD

**Issue by valeeeriquelme** [IIC2513/Syllabus#94]
Para manejar los errores de cors deben añadir cors a su package (yarn add @koa/cors) y las siguientes líneas a su código en el back (app.js) 

const cors = require('@koa/cors');  

const corsOptions ={ origin:'http://localhost:8000',  credentials:true, optionSuccessStatus:200 } 
app.use(cors(corsOptions)); //previo a añadir el router 

(el 8000 es porque desde ahí llegan las consultas del front, deben cambiar según el puerto que usen)

**Comment by gecoli** [comment]
Bueno, me servía con koa-static y con esto no, ¿Hay alguna otra opción de cómo lidiar con esto? tengo problemas incluso con el GET

**Comment by EleaTriesToCode** [comment]
Hola, lo siento pero todavia eso no me funciona... 
Lo que hice es cambiar las lineas por : 
const corsOptions ={ origin:'*', credentials:true,optionSuccessStatus:200}
app.use(cors(corsOptions));

Estoy autorizando todas las rutas posibles, y estoy conciente de que eso puede causar problemas de seguridad.... 
Esta posible hacer eso ?

Por si acaso, el error que siempre me sale es por ejemplo:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/sumar/8/5. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘http://localhost:3000’)

Quizas el problema viene de la manera con cual hago mis fetch. Dejo un ejemplo de como lo estoy haciendo : 
const response = await fetch('http://localhost:3000/dividir', ... etc ...
Eso quizas no es una manera correcta de hacer fetch ?
