### ISSUE TITLE
Como enviar status

### ISSUE THREAD

**Issue by gvfigueroa** [IIC2513/Syllabus#95]
Hola!
Tengo una duda en como enviar el status como respuesta en caso de división por 0. Deberíamos "forzar" a que el backend de error? por ejemplo con ctx.status = 400?. O se debería enviar de la forma ctx.body = {status: 400, resultado: "Error: bla"}; cosa de que la respuesta se envíe correctamente, pero que en el frontend la analicemos y revisemos si el resultado tuvo un error?

**Comment by HernanCabrera** [comment]
Este es un manejo de error de afiliación, no de protocolo, en ese caso en el JSON debe decir que es un error pero es un uso exitoso del próximo y la función
Es decir, la adoración responde y responder que dividir por veo vi esta permitido no es un error de HTTP si no una operación detectada como invalida.
Espero se entienda :)
