### ISSUE TITLE
[T3] Problemas para hacer fetch desde el front usando dotenv en el back

### ISSUE THREAD

**Issue by Dirial** [IIC2513/Syllabus#96]
Hola, tengo un problema con la operación fetch que se hace desde el front. Lo que pasa es que cuando utilizo dotenv en el back, para inicializar el server en el puerto que está en el archivo .env, no puedo enviarle las solicitudes, me sale el error net::ERR_CONNECTION_REFUSED, pero cuando en el back no uso el .env si puedo escuchar las solicitudes que me hace el front.

Otra duda que tenia es que si era necesario utilizar un puerto para el front, yo solo abro el archivo index.html de mi front y si el server del back esta inicializado entonces le puedo mandar las solicitudes. De hecho en las opciones de cors, tengo la llave origin con el valor '', es decir `{origin: ''}`, en vez de tenerlo con algún puerto, y funciona bien. No se si eso es bueno o tengo que cambiar algo.

**Comment by valeeeriquelme** [comment]
añadiste dotenv a tu package (con yarn add dotenv)??

**Comment by Dirial** [comment]
Lo hice, pero solo en en el back ya que pensé que solo el back tenia que ser inicializado con yarn, el front también debe ser inicializado con yarn?

**Comment by valeeeriquelme** [comment]
Ya, lo que pasa es que lo que haces e instalas a nivel de back no tiene nada quee veer con lo que haces a nivel de front (en este caso que estamos construyndo una api). 

Una duda, estás usando react?

**Comment by Dirial** [comment]
No, estoy usando solo html, js y css, sin ninguna otra libreria.

**Comment by valeeeriquelme** [comment]
En ese caso lo de las variables de entorno con dotenv aplica solo para back. Para front manéjalas como constantes.

**Comment by Dirial** [comment]
Ya encontré el problema, se me había olvidado poner `import 'dotenv/config'` en el index, muchas gracias por la ayuda.
