### ISSUE TITLE
[Tarea 3] Duda sobre uso de async function con await y sobre programacion en ingles

### ISSUE THREAD

**Issue by NicolasOlmosQuiroga** [IIC2513/Syllabus#97]
¡Hola!, tenia dos preguntas:

1. ¿Es necesario que en el frontend, para hacer el fetch, se use async function junto con await?, por mi parte yo lo estaba haciendo como una funcion normal con fetch para obtener los resultados pero no sabia si era necesario usar async con wait.

2. ¿Se puede programar en ingles?, en mi tarea defini todo en ingles, desde las funciones, las rutas (en vez de "/suma/" use "/addition/"), los errores estan en ingles, etc. Para mi era mas comodo asi pero no sabia si esto iba a hacer que se me descontara puntaje.

Eso seria, ¡muchas gracias!

**Comment by valeeeriquelme** [comment]
Como sería una función normal fetch sin async y await??

sobre si es en inglés o en español, no hay problema, elige lo que te acomode.

**Comment by NicolasOlmosQuiroga** [comment]
Hice el frontend en React, y en el archivo .jsx donde tengo la "calculadora", tengo una funcion que detecta si se clickea el boton = y es algo asi:

```
 function x() {
      if y {
        fetch(url, {
          method: 'z',
        })
          .then((response) => response.json())
          .then((data) => {
            if (data.status === 'success') {
            } else {
              console.error('Error:', data.result);
            }
          })
          .catch((error) => {
            console.error('Error:', error);
          });
      }
```
Intente simplificarlo lo mas que pude para no tener que mostrar mas codigo, esto estaba haciendo y funciona perfectamente, pero aun asi tenia la duda de que si estaba mal o no.

**Comment by valeeeriquelme** [comment]
el objtivo de ocupar async/await es poder manjar las asincronias aociadas a recibir la request. Si estás manejandolo de otra forma, no hay problema (siempr y cuando lo manejes).
