### ISSUE TITLE
Error al comprimir tarea a zip

### ISSUE THREAD

**Issue by agustind1** [IIC2513/Syllabus#98]
Hola! cuando trato de comprimir mi tarea a zip me aparece un error  "archivo no encontrado o falta permiso de lectura" , parece que tiene relación con archivos de node porque la única carpeta que se puede comprimir es la del back por falta de permisos a algunos archivos. ¿Que puedo hacer para solucionarlo? 
![Captura de pantalla 2023-05-18 172221](https://github.com/IIC2513/Syllabus/assets/89109447/75ada54c-b0c2-455e-bf25-60bb105c1697)

**Comment by aaossa** [comment]
Probablemente ocurra porque usaste un permiso superior para crear la carpeta node_modules. Si usaste un *package manager*, probablemente tengas un `package.json` y eso debería ser suficiente para crear de nuevo `node_modules`, por lo que puedes eliminar esa carpeta y tratar de comprimir el código (y los archivos necesarios para construir el entorno, como `package.json`). 

Prueba copiando todos los contenidos de tu tarea **excepto `node_modules`** y ve si es que puedes volver a levantarla. Si necesitas usar algún comando de `npm` o `vite`, agregalo en el README indicando los pasos para probar tu código

**Comment by nolate26** [comment]
A mi me tira el siguiente error y nose como arreglarlo.
![WhatsApp Image 2023-05-19 at 15 05 37](https://github.com/IIC2513/Syllabus/assets/80768615/c3096c93-ccdf-4c56-aa78-229f8cfd848f)

**Comment by paulmacguire** [comment]
> A mi me tira el siguiente error y nose como arreglarlo. ![WhatsApp Image 2023-05-19 at 15 05 37](https://user-images.githubusercontent.com/80768615/239615244-c3096c93-ccdf-4c56-aa78-229f8cfd848f.jpeg)

Me pasa lo mismo que a él, no logro comprimir el archivo a .zip .

**Comment by nolate26** [comment]
> > A mi me tira el siguiente error y nose como arreglarlo. ![WhatsApp Image 2023-05-19 at 15 05 37](https://user-images.githubusercontent.com/80768615/239615244-c3096c93-ccdf-4c56-aa78-229f8cfd848f.jpeg)
> 
> Me pasa lo mismo que a él, no logro comprimir el archivo a .zip .

Borra las carpetas de node_modules y en el README pide que ejecuten eso, ahí si me funcionó!
