### ISSUE TITLE
[T3] Servidor para front

### ISSUE THREAD

**Issue by Dafnemami** [IIC2513/Syllabus#99]
Hola!, 

Estoy un poco perdida con lo de levantar un servidor para front. Me podrían guiar un poco? Así como la idea de como comunicar eso con back (entiendo que es a través de una api como en el taller de koa) Yo ocupé html+css+js para front.

Saludos!!

**Comment by tzehnder** [comment]
tengo una duda similar, pense en usar vite, como para la entrega uno del proyecto, pero nose si eso se puede hacer.
Me paso que cree los componentes para la calculadora con react pero no los podia visualizar bien con live server, por lo que probe con vite y si los pude visualizar. 
Esta mal eso o si se puede hacer?

**Comment by aaossa** [comment]
Siguiendo la respuesta en https://github.com/IIC2513/Syllabus/issues/88 :

> (...) Con que especifiques en el readme como se deben ejecutar tus archivos está ok.

**Comment by tzehnder** [comment]
Gracias! creo que ya voy entendiendo mejor como estructurar la tarea, me queda una unica duda, investigando vi que podria ser que al usar vite no sea tan facil editar el front end con las respuestas del back.
por ejemplo si creo un fetch para la suma dentro de los handlers de mi calculadora en react, luego en el backend calculo y actualizo el body, entregando al fetch los resultados y seteando esos en el display. 
seria correcta esa aproximacion o mi desarrollo en vite podria presentar problemas?
